[package]
name = "HarunaBot2"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
serde_json = "1.0.151"
tracing = "0.1.44"
anyhow = "1.0.104"
tracing-subscriber = "0.3.23"
reqwest = { version = "0.13.4", features = ["json"] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-tungstenite = "0.30.0"
futures-util = "0.3.34"
tungstenite = "0.30.0"
async-trait = "0.1.92"